package com.example.aschmelz.opengl2048;

/**
 * Created by aschmelz on 23/03/2018.
 */


import static com.example.aschmelz.opengl2048.ImgConsts.*;


public class FontConstants {

    public static final int FONT_CHAR[] = new int[] {

            FONT_MARRYTODD_33,
            FONT_MARRYTODD_34,
            FONT_MARRYTODD_35,
            FONT_MARRYTODD_36,
            FONT_MARRYTODD_37,
            FONT_MARRYTODD_38,
            FONT_MARRYTODD_39,
            FONT_MARRYTODD_40,
            FONT_MARRYTODD_41,
            FONT_MARRYTODD_42,
            FONT_MARRYTODD_43,
            FONT_MARRYTODD_44,
            FONT_MARRYTODD_45,
            FONT_MARRYTODD_46,
            FONT_MARRYTODD_47,
            FONT_MARRYTODD_48,
            FONT_MARRYTODD_49,
            FONT_MARRYTODD_50,
            FONT_MARRYTODD_51,
            FONT_MARRYTODD_52,
            FONT_MARRYTODD_53,
            FONT_MARRYTODD_54,
            FONT_MARRYTODD_55,
            FONT_MARRYTODD_56,
            FONT_MARRYTODD_57,
            FONT_MARRYTODD_58,
            FONT_MARRYTODD_59,
            FONT_MARRYTODD_60,
            FONT_MARRYTODD_61,
            FONT_MARRYTODD_62,
            FONT_MARRYTODD_63,
            FONT_MARRYTODD_64,
            FONT_MARRYTODD_65,
            FONT_MARRYTODD_66,
            FONT_MARRYTODD_67,
            FONT_MARRYTODD_68,
            FONT_MARRYTODD_69,
            FONT_MARRYTODD_70,
            FONT_MARRYTODD_71,
            FONT_MARRYTODD_72,
            FONT_MARRYTODD_73,
            FONT_MARRYTODD_74,
            FONT_MARRYTODD_75,
            FONT_MARRYTODD_76,
            FONT_MARRYTODD_77,
            FONT_MARRYTODD_78,
            FONT_MARRYTODD_79,
            FONT_MARRYTODD_80,
            FONT_MARRYTODD_81,
            FONT_MARRYTODD_82,
            FONT_MARRYTODD_83,
            FONT_MARRYTODD_84,
            FONT_MARRYTODD_85,
            FONT_MARRYTODD_86,
            FONT_MARRYTODD_87,
            FONT_MARRYTODD_88,
            FONT_MARRYTODD_89,
            FONT_MARRYTODD_90,
            FONT_MARRYTODD_91,
            FONT_MARRYTODD_92,
            FONT_MARRYTODD_93,
            FONT_MARRYTODD_94,
            FONT_MARRYTODD_95,
            FONT_MARRYTODD_96,
            FONT_MARRYTODD_97,
            FONT_MARRYTODD_98,
            FONT_MARRYTODD_99,
            FONT_MARRYTODD_100,
            FONT_MARRYTODD_101,
            FONT_MARRYTODD_102,
            FONT_MARRYTODD_103,
            FONT_MARRYTODD_104,
            FONT_MARRYTODD_105,
            FONT_MARRYTODD_106,
            FONT_MARRYTODD_107,
            FONT_MARRYTODD_108,
            FONT_MARRYTODD_109,
            FONT_MARRYTODD_110,
            FONT_MARRYTODD_111,
            FONT_MARRYTODD_112,
            FONT_MARRYTODD_113,
            FONT_MARRYTODD_114,
            FONT_MARRYTODD_115,
            FONT_MARRYTODD_116,
            FONT_MARRYTODD_117,
            FONT_MARRYTODD_118,
            FONT_MARRYTODD_119,
            FONT_MARRYTODD_120,
            FONT_MARRYTODD_121,
            FONT_MARRYTODD_122,
            FONT_MARRYTODD_123,
            FONT_MARRYTODD_124,
            FONT_MARRYTODD_125,
            FONT_MARRYTODD_126,
    };
}
